In [1]:
import pandas as pd
import numpy as np
import io
from pandas import read_excel
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from matplotlib import pyplot as plt
from scipy import misc
%matplotlib inline

In [2]:
data=pd.read_csv(r"LungDataSet.csv")

In [3]:
data.head()

Patient Id  Age  Gender  AirPollution  Alcoholuse  DustAllergy  \
0         P1   33       1             2           4            5   
1        P10   17       1             3           1            5   
2       P100   35       1             4           5            6   
3      P1000   37       1             7           7            7   
4       P101   46       1             6           8            7   

   OccuPationalHazards  GeneticRisk  chronicLungDisease  BalancedDiet  ...  \
0                    4            3                   2             2  ...   
1                    3            4                   2             2  ...   
2                    5            5                   4             6  ...   
3                    7            6                   7             7  ...   
4                    7            7                   6             7  ...   

   Fatigue  WeightLoss  ShortnessofBreath  Wheezing  SwallowingDifficulty  \
0        3           4                  2         2                     3   
1        1           3                  7         8                     6   
2        8           7                  9         2                     1   
3        4           2                  3         1                     4   
4        3           2                  4         1                     4   

   ClubbingofFingerNails  FrequentCold  DryCough  Snoring   Level  
0                      1             2         3        4     Low  
1                      2             1         7        2  Medium  
2                      4             6         7        2    High  
3                      5             6         7        5    High  
4                      2             4         2        3    High  

[5 rows x 25 columns]

In [4]:
data.shape

(1000, 25)

In [5]:
data.columns

Index(['Patient Id', 'Age', 'Gender', 'AirPollution', 'Alcoholuse',
       'DustAllergy', 'OccuPationalHazards', 'GeneticRisk',
       'chronicLungDisease', 'BalancedDiet', 'Obesity', 'Smoking',
       'PassiveSmoker', 'ChestPain', 'CoughingofBlood', 'Fatigue',
       'WeightLoss', 'ShortnessofBreath', 'Wheezing', 'SwallowingDifficulty',
       'ClubbingofFingerNails', 'FrequentCold', 'DryCough', 'Snoring',
       'Level'],
      dtype='object')

In [6]:
data.isnull().sum()

Patient Id               0
Age                      0
Gender                   0
AirPollution             0
Alcoholuse               0
DustAllergy              0
OccuPationalHazards      0
GeneticRisk              0
chronicLungDisease       0
BalancedDiet             0
Obesity                  0
Smoking                  0
PassiveSmoker            0
ChestPain                0
CoughingofBlood          0
Fatigue                  0
WeightLoss               0
ShortnessofBreath        0
Wheezing                 0
SwallowingDifficulty     0
ClubbingofFingerNails    0
FrequentCold             0
DryCough                 0
Snoring                  0
Level                    0
dtype: int64

In [7]:
features = ["Age", "Gender", "AirPollution", "Alcoholuse", "DustAllergy", "OccuPationalHazards", "GeneticRisk", "chronicLungDisease", "BalancedDiet", "Obesity", "Smoking", "PassiveSmoker", "ChestPain", "CoughingofBlood", "Fatigue", "WeightLoss", "ShortnessofBreath", "Wheezing", "SwallowingDifficulty", "ClubbingofFingerNails", "FrequentCold", "DryCough", "Snoring"]

In [8]:
data['Level'].unique()

array(['Low', 'Medium', 'High'], dtype=object)

In [9]:
train, test = train_test_split(data, test_size = 0.3)
print("Total Data set ",len(data))
print("Traning Dataset",len(train))
print("Test Dataset", len(test))

Total Data set  1000
Traning Dataset 700
Test Dataset 300


In [11]:
x_train = train[features]
y_train = train["Level"]

x_test = test[features]
y_test = test["Level"]

In [12]:
c = GaussianNB()
dt = c.fit(x_train, y_train)

In [13]:
y_pred = c.predict(x_test)
y_pred

array(['Low', 'High', 'Low', 'Low', 'High', 'Medium', 'High', 'High',
       'High', 'High', 'Low', 'High', 'Low', 'Low', 'High', 'High',
       'High', 'Low', 'Medium', 'High', 'Medium', 'High', 'High',
       'Medium', 'Medium', 'High', 'High', 'High', 'Medium', 'Medium',
       'Low', 'Low', 'Low', 'High', 'Low', 'High', 'Medium', 'High',
       'Low', 'Low', 'Medium', 'Medium', 'Low', 'High', 'Medium', 'High',
       'Medium', 'Medium', 'High', 'High', 'High', 'High', 'Low',
       'Medium', 'Medium', 'High', 'Medium', 'Low', 'Medium', 'High',
       'High', 'High', 'Low', 'Medium', 'High', 'High', 'High', 'High',
       'High', 'Medium', 'High', 'Low', 'Low', 'Low', 'High', 'High',
       'Low', 'Low', 'High', 'Medium', 'Medium', 'Medium', 'High', 'Low',
       'High', 'High', 'High', 'Low', 'High', 'Low', 'Medium', 'High',
       'Low', 'Low', 'High', 'Medium', 'High', 'High', 'Low', 'Low',
       'High', 'Medium', 'Low', 'High', 'Low', 'High', 'High', 'Medium',
       'High', 'H

In [14]:
score = accuracy_score(y_test, y_pred)*100
acc = round(score,2)
inac = round(100-acc,2)
corr = (score*len(test))/100
print("Accuracy: ", acc, "%, ", corr, "Correct Predictions")
print("Inaccuracy: ", inac, "%, ", len(test)-corr, "Incorrect Predictions")

Accuracy:  89.33 %,  268.0 Correct Predictions
Inaccuracy:  10.67 %,  32.0 Incorrect Predictions


In [15]:
print(confusion_matrix(y_test, y_pred))

[[112   0   3]
 [  7  86   6]
 [ 16   0  70]]


In [16]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        High       0.83      0.97      0.90       115
         Low       1.00      0.87      0.93        99
      Medium       0.89      0.81      0.85        86

    accuracy                           0.89       300
   macro avg       0.91      0.89      0.89       300
weighted avg       0.90      0.89      0.89       300

